#URI_dalien = 'mongodb://tor_wf:Yr6A2BZbxRS7@:37017/tor_wf?readPreference=primary'
#URI_dnetcloud = 'mongodb://tor_wf:Yr6A2BZbxRS7@172.17.53.15:27017/tor_wf?readPreference=primary'
dbname = 'tor_wf'
user = 'tor_wf'
pswd = 'Yr6A2BZbxRS7'
host = 'dalien.cs.kuleuven.be'
port = '37017'
colname_base = 'tor_open_'
visits_per_batch = 100
outdir = "/data/tor/time-6w"
runs = 2
sep = ";"
#openw = True
openw = False
